FROM node:lts AS builder 
WORKDIR /build 
COPY src ./src
COPY package*.json ./
COPY tsconfig.json ./
RUN npm ci
RUN npm run build

FROM node:lts-alpine

WORKDIR /server

COPY package*.json ./
COPY docker/index.js ./
RUN npm ci --production
COPY --from=builder /build/dist/ /server/dist/

ENV DEV=true

EXPOSE 8080
ENV PORT=8080
ENV BASE_URL=/
ENV SAVE_PATH=/uploads
ENV FILENAME_LENGTH=10
ENV ENABLE_SXCU=TRUE
ENV TRUST_PROXY=TRUE
ENV DEBUG=FALSE
ENV FORCE_HTTPS=
ENV FILE_LISTING=/files

CMD ["node", "index.js"]